### ISSUE TITLE
bot is not working ... 

### ISSUE THREAD

**Issue by ghost** [Apress/building-chatbots-with-python#1]
https://horoscopebot1212.herokuapp.com/webhooks/rasa/chat

not reply from the bot. Tks.

**Comment by sumit12dec** [comment]
Hey @delonleo 
Request you to please leave a review on Amazon about your experience of the book.
https://amazon.com/Building-Chatbots-Python-Language-Processing/dp/1484240952

You can also ask any questions related to chatbots or the book in the discussion forum created for book readers.

https://buildingchatbotswithpython.sumitraj.in/
